export const AUTH_SESSION_COOKIE = 'ocpool_session';

export const PERMISSION_CATALOG = [
  { key: 'identity.session.read', description: 'Consultar sesiones propias o autorizadas.' },
  { key: 'identity.session.revoke', description: 'Revocar sesiones de usuarios autorizados.' },
  { key: 'identity.users.read', description: 'Consultar usuarios autorizados.' },
  { key: 'identity.users.manage', description: 'Administrar usuarios y estados de acceso.' },
  { key: 'identity.roles.manage', description: 'Administrar roles y permisos.' },
  { key: 'portal.self.read', description: 'Consultar la información propia del portal.' },
  { key: 'portal.self.authenticate', description: 'Autenticarse en el portal del cliente.' },
  { key: 'messaging.read', description: 'Consultar conversaciones autorizadas.' },
  { key: 'messaging.send', description: 'Enviar mensajes compartidos con el cliente.' },
  { key: 'messaging.internal_notes.read', description: 'Consultar notas internas autorizadas.' },
  { key: 'messaging.internal_notes.write', description: 'Crear notas internas autorizadas.' },
  { key: 'messaging.manage', description: 'Cerrar o reabrir conversaciones autorizadas.' },
  { key: 'files.read', description: 'Consultar archivos autorizados del expediente.' },
  { key: 'files.upload', description: 'Cargar archivos autorizados al expediente.' },
  { key: 'files.download', description: 'Descargar archivos autorizados del expediente.' },
  { key: 'files.delete', description: 'Borrar lógicamente archivos propios autorizados.' },
  { key: 'files.internal.read', description: 'Consultar archivos internos del expediente.' },
  { key: 'files.manage', description: 'Administrar archivos y retención del expediente.' },
  { key: 'requests.read', description: 'Consultar solicitudes autorizadas.' },
  { key: 'requests.read.global', description: 'Consultar solicitudes globales y carga por responsable.' },
  { key: 'requests.create', description: 'Crear solicitudes comerciales.' },
  { key: 'requests.assign', description: 'Asignar solicitudes a responsables.' },
  { key: 'requests.edit', description: 'Editar datos comerciales de solicitudes.' },
  { key: 'requests.reassign', description: 'Reasignar solicitudes que ya tienen responsable.' },
  { key: 'requests.status.update', description: 'Cambiar el estado de solicitudes autorizadas.' },
  { key: 'catalog.read', description: 'Consultar el catálogo comercial autorizado.' },
  { key: 'catalog.manage', description: 'Administrar conceptos y categorías del catálogo.' },
  { key: 'prices.read', description: 'Consultar listas y precios vigentes autorizados.' },
  { key: 'prices.manage', description: 'Administrar listas, vigencias y precios comerciales.' },
  { key: 'quotes.read', description: 'Consultar solicitudes y cotizaciones autorizadas.' },
  { key: 'quotes.create', description: 'Crear solicitudes o cotizaciones.' },
  { key: 'quotes.edit_prices', description: 'Modificar precios de cotización.' },
  { key: 'quotes.apply_discount', description: 'Aplicar descuentos a cotizaciones.' },
  { key: 'quotes.approve_discount', description: 'Aprobar descuentos que requieren autorización.' },
  { key: 'quotes.send', description: 'Enviar cotizaciones al cliente.' },
  { key: 'quotes.pdf.read', description: 'Descargar documentos PDF de cotizaciones autorizadas.' },
  { key: 'quotes.pdf.generate', description: 'Generar y regenerar documentos PDF de cotizaciones.' },
  { key: 'quotes.accept', description: 'Aceptar cotizaciones autorizadas en nombre del cliente.' },
  { key: 'notifications.read', description: 'Consultar el estado operativo de notificaciones autorizadas.' },
  { key: 'notifications.manage', description: 'Reintentar o administrar entregas de notificaciones autorizadas.' },
  { key: 'metrics.read', description: 'Consultar métricas operativas.' },
  { key: 'metrics.read.global', description: 'Consultar métricas operativas globales y carga por responsable.' },
  { key: 'audit.read', description: 'Consultar actividad operativa auditada.' },
  { key: 'audit.security.read', description: 'Consultar eventos de seguridad e identidad auditados.' },
] as const;

export const ROLE_DEFINITIONS = {
  customer: {
    name: 'Cliente',
    description: 'Acceso al portal propio del cliente.',
    systemManaged: true,
    permissions: ['portal.self.read', 'portal.self.authenticate', 'identity.session.read', 'messaging.read', 'messaging.send', 'files.read', 'files.upload', 'files.download', 'files.delete', 'quotes.pdf.read', 'quotes.accept'],
  },
  sales: {
    name: 'Ventas',
    description: 'Operación comercial de solicitudes y cotizaciones.',
    systemManaged: true,
    permissions: [
      'identity.session.read',
      'identity.session.revoke',
      'identity.users.read',
      'portal.self.read',
      'messaging.read',
      'messaging.send',
      'messaging.internal_notes.read',
      'messaging.internal_notes.write',
      'files.read',
      'files.upload',
      'files.download',
      'files.delete',
      'files.internal.read',
      'requests.read',
      'requests.create',
      'requests.assign',
      'requests.edit',
      'requests.status.update',
      'catalog.read',
      'prices.read',
      'quotes.read',
      'quotes.create',
      'quotes.send',
      'quotes.pdf.read',
      'quotes.pdf.generate',
      'notifications.read',
      'metrics.read',
    ],
  },
  manager: {
    name: 'Gerencia',
    description: 'Supervisión comercial y aprobación de descuentos.',
    systemManaged: true,
    permissions: [
      'identity.session.read',
      'identity.session.revoke',
      'identity.users.read',
      'identity.users.manage',
      'portal.self.read',
      'messaging.read',
      'messaging.send',
      'messaging.internal_notes.read',
      'messaging.internal_notes.write',
      'messaging.manage',
      'files.read',
      'files.upload',
      'files.download',
      'files.delete',
      'files.internal.read',
      'files.manage',
      'requests.read',
      'requests.read.global',
      'requests.create',
      'requests.assign',
      'requests.edit',
      'requests.reassign',
      'requests.status.update',
      'catalog.read',
      'catalog.manage',
      'prices.read',
      'prices.manage',
      'quotes.read',
      'quotes.create',
      'quotes.send',
      'quotes.edit_prices',
      'quotes.apply_discount',
      'quotes.approve_discount',
      'quotes.pdf.read',
      'quotes.pdf.generate',
      'notifications.read',
      'notifications.manage',
      'metrics.read',
      'metrics.read.global',
      'audit.read',
    ],
  },
  admin: {
    name: 'Administrador',
    description: 'Administración completa de la plataforma con MFA obligatorio.',
    systemManaged: true,
    permissions: PERMISSION_CATALOG.map(({ key }) => key),
  },
} as const;

export const AUTH_POLICY = {
  password: {
    algorithm: 'argon2id',
    memoryCostKiB: 19_456,
    timeCost: 2,
    parallelism: 1,
    outputLength: 32,
  },
  opaqueTokenBytes: 32,
  encryption: {
    algorithm: 'aes-256-gcm',
    ivBytes: 12,
  },
} as const;
