-- Corrective migration: 20260917193719_notification_cancel_reason_contact_email_changed
-- was auto-generated by `prisma migrate dev` alongside the intentional cancel-reason
-- constraint change requested in this session. As before (see
-- 20260915192000_restore_quote_pointer_integrity_constraints), these two composite FKs
-- (added by 20260911094000_quote_pointer_integrity) have no declarative representation
-- in schema.prisma, so Prisma's diff engine did not recognize them as intentional and
-- emitted DROP CONSTRAINT statements for them again. This restores them directly.
ALTER TABLE "quotes"
  ADD CONSTRAINT "quotes_working_version_same_quote_fk"
    FOREIGN KEY ("workingVersionId", "id") REFERENCES "quote_versions" ("id", "quoteId") ON DELETE SET NULL ("workingVersionId") ON UPDATE CASCADE,
  ADD CONSTRAINT "quotes_published_version_same_quote_fk"
    FOREIGN KEY ("publishedVersionId", "id") REFERENCES "quote_versions" ("id", "quoteId") ON DELETE SET NULL ("publishedVersionId") ON UPDATE CASCADE;
