-- Corrective migration: 20260915191152_special_concept_lines was auto-generated by
-- `prisma migrate dev` and, because these two composite FKs (added by
-- 20260911094000_quote_pointer_integrity) have no declarative representation in
-- schema.prisma, Prisma's diff engine did not recognize them as intentional and
-- emitted DROP CONSTRAINT statements for them. That was caught and the constraints
-- were restored directly on the database before this migration was written, so this
-- migration only records that restoration in migration history — it does not run
-- against the database (applied via `prisma migrate resolve --applied`).
ALTER TABLE "quotes"
  ADD CONSTRAINT "quotes_working_version_same_quote_fk"
    FOREIGN KEY ("workingVersionId", "id") REFERENCES "quote_versions" ("id", "quoteId") ON DELETE SET NULL ("workingVersionId") ON UPDATE CASCADE,
  ADD CONSTRAINT "quotes_published_version_same_quote_fk"
    FOREIGN KEY ("publishedVersionId", "id") REFERENCES "quote_versions" ("id", "quoteId") ON DELETE SET NULL ("publishedVersionId") ON UPDATE CASCADE;
